# -*- coding: utf-8 -*-
"""20512심완기_리스트.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19mMxSBrL6HcEDUh1MX8MoGCBUUzDprdR
"""

#리스트
colors=['red','blue','green']
print(colors)
print(type(colors))
print(colors[0])
print(colors[1])
print(colors[2])
print(colors[-1])
print(colors[-2])
print(colors[-3])

"""22page"""

#ex01
price = [500, 5000, 8900, 1800, 2500]
fruit = ['사과', '파인애플', '수박']
print(price)
print(type(price))
print(fruit)
print(type(fruit))

#ex02
fruit = ['사과', 1500, '수박', 8900]
print(fruit)
print('사과의 자료형은',type(fruit[0]),'이다')
print('1500의 자료형은',type(fruit[1]),'이다')
print('수박의 자료형은',type(fruit[2]),'이다')
print('8900의 자료형은',type(fruit[3]),'이다')

#ex03
a=[]
b=list()
print(a)
print(b)
print(type(a))
print(type(b))

#ex04
num = list(range(1,23, 2))
a = list("korea")
print(num)
print(type(num))
print(a)
print(type(a))

#ex05\
num = [88, 95, 70, 100, 99, 80, 78,50,90,20]
a = [88, 95, 70, 100, 99]
print(len(num))
print(len(a))

#ex06
score = [88, 95, 70, 100, 99, 80, 78,50]
print('학생수', len(score), "명")
print('최고 점수', max(score), "점")
print('최저 점수', min(score), "점")

#ex07
score = [88, 95, 70, 100, 99]
print(score[-5],score[-4],score[-3],score[-2])
print(score[-1],score[-2],score[-3],score[-4])

#ex08
score = [88, 95, 70, 100, 99]
score[0]=10
score[1]=20
score[2]=30
score[3]=40
score[4]=50
print(score)

#ex09)
animals = ['토끼', '거북이', '사자', '호랑이']
print(animals[1:3])

i = 0
while i<len(animals):
  print(animals[i])
  i +=1

#ex 10
nums =[0,1,2,3,4,5,6,7,8,9]

print(nums[2:5:1])
print(nums[1:6:2])
print(nums[0:5:2])

#ex11
nums =[0,1,2,3,4,5,6,7,8,9]
print(nums[:5:1])
print(nums[:7:2])
print(nums[:5:2])

#ex12
nums =[0,1,2,3,4,5,6,7,8,9]
print(nums[2::1])
print(nums[1::2])
print(nums[0::2])

#ex 13
nums =[0,1,2,3,4,5,6,7,8,9]

print(nums[2:5])
print(nums[1:7])
print(nums[0:5])

#ex 14
fruits = ['사과', '오렌지', '딸기', '포도', '감', '키위', '멜론', '수박']
print(fruits[0])
print(fruits[2:8])
print(fruits[7])
print(fruits[4:6])
print(fruits[5:8])

#ex15
print("korea")
print(list("korea"))

#ex 16
my_list = list("PythonIsFun!")
print(list(my_list))
print(list(my_list[2:5:1]))
print(list(my_list[3:6:1]))
print(list(my_list[2:7:1]))
print(list(my_list[4:9:1]))

#ex17
s = "python"

print(s[3])
print(s[4])
print(s[1:4:1])

#ex 18
file = "20210505-104830.jpg"
print('찰영날짜',file[4:6:1],'월',file[6:8:1],'일')
print('찰영시간',file[9:11:1],'시',file[11:13:1],'분')
print('확장자:',file[16:19:1])

#ex 19
s="차종: 코란도C, 제조사:쌍용, 배기량: 1998"
print(s[14:16:1])

#ex20
jumin = "901231-1914983"
year = jumin[0:2:1]
if jumin[6]==0:
  gender = "여자"
else:
  gender = "남자"


print("{}년생 {}입니다.".format(year, gender))

#요소추가
nums=[1,2,3,4]
nums.append(5)
print(nums)

#요소삽입
nums.insert(2,99)
print(nums)

#ex21
list1 = [1,2,3,4,5]
list2 = [10,11]
list1.extend(list2)
print(list1)

#ex22
score = [88,95, 70, 100, 99]
print("100의 위치", score.index(100)+1)

print(score.pop())
print(score.pop())
print(score.pop(1))
print(score)

#ex24
score = [88,95, 70, 100, 99]
score.remove(99)
print("99삭제 후 :",score)
score.sort()
print("리스트 정렬 후(오름차순) :",score)
score.sort(reverse=True)
print("거꾸로 정렬(내림차순) :",score)
score.clear()
print("리스트 삭제 :",score)

list1 = ['a', 'bb', 'c', 'd','aaa','c','ddd','aaa', 'b', 'cc', 'd', 'aaa',]
print(list1.count('aaa'))

#ex26
mylist = ['사과', '바나나', '파인애플']
mylist.append('키위')
mylist.append('배')
for m in mylist:
  print(m)

#ex27
scores=[]

while True :
  score = int(input("성적을 입력하세요(종료 : -1):"))
  if

  else

pritnt(scores)