# -*- coding: utf-8 -*-
"""20512_06/08_p34,ex27.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Rq6zllnWrt6JGAaIKBw_3e_lVyPHDETA
"""

#p31_ex1

s='python'
print(s)
print(s[0])
print(s[-1])

#ex2
print(s[10])

#ex3
s1 = str(input("문자열 입력 :"))
s2 = str(input("문자열 입력 :"))
s3 = str(input("문자열 입력 :"))

if s1[-1] == s2[0] and s2[-1] == s3[0]:
  print("good")
else:
  print("bad")

#ex4
s = "python"
for i in range(len(s)):
  print(s[i], end=' ')

#ex5
number = input('하이폰(-)을 포함한 휴대번호를 입력하세요 : ')
for i in range(len(number)):
  print(number[i], end=' ')

#ex6
s = "python"

n = "여섯글자이다"
print(len(s))
print(len(n))

#ex7
sentance = input("문자열 입력 : ")
k =0

for i in range(len(sentance)):
  if sentance[i] == "t":
    k+=1

print(k)
print(len(sentance))

#ex08
sentance = input("문자열 입력 : ")
i = len(sentance)-1
while i>=0:
  if sentance[i] == ' ':
    print('-', end='')
  else:
    print('%s'%sentance[i], end='')
  i-=1

#ex09
data = input("문자열 입력: ")

for i in range(len(data)-1):
  print(data[i], data[i+1], sep ='')

#ex10
s ="python"
print(s[2:5])
print(s[3:])
print(s[:4])
print(s[2:-2])
print(s[-2])

#ex11
s = "차종: 코란도C, 제조사:쌍용, 배기량: 1998"
print(s[14:16])

#ex12
file = "20210505-104830"
print("찰영날짜: "+file[4:6]+"월"+file[6:8]+"일")
print("찰영시간: "+file[14:16]+"시"+file[14:16]+"분")
print("확장자:"+file[14:16])

#ex13
yoil = "월화수목금토일"
print(yoil[::-1])
print(yoil[::2])

#ex14
jumin = "901231-1914983"
year = 0

#ex15
a = "10 20 30 40 50"

b = "나는 서울로봇고 2학년이야"
a.split()
b.split()

#ex16
a = "a:b:c:d"
a.split(':')

#ex17
BTS = "정국, 진, 뷔, 슈가, 지민, RM,제이홉"
BTS_member = BTS.split(',')
print("방탄맴버: ", BTS_member)

for i in range(len(BTS_member)):
  print(BTS_member[i]+" 사랑해")

#ex18
file_names = ["file1.py", "file2.txt", "file3.pptx", "file4.doc"]

for file_name in file_names:
  arr = file_name.split(".") #arr[0]=file1, arr[1]=py
  print(f'{file_name:11}=> 파일명:{arr[0]}, 확장자{arr[1]}')

#ex19
sentence = input("문자열 입력: ")
a = sentence.split()
for i in range(len(a)):
#for i in a
  print(print(a[i], end =''))

#ex20
print(",".join('abcd'))
print("::".join( ["1", "2", "3", "4", "5"]))

#ex21
s = "python programming"

print("문자열 s의 길이 =", len(s))
print()
print("문자열 s에서 o의 인덱스 =", s.find('o'))
print("문자열 s에서 o의 인덱스 =", s.find('o',5))
print("문자열 없는 인덱스를 검색 =", s.find('A'))
print("o를 뒤에서부터 검색한 인덱스 =", s.rfind('o'))
print()
print("문자열 s에서 r의 인덱스 =", s.index('r'))
print("문자열 s에서 n의 개수 =", s.count('n'))
print()
print("문자열 s에서 gram의 인덱스 =", s.find('gram'))
print("문자열 s에서 gram의 개수 =", s.index('gram'))
print("문자열 s에서 gram의 개수 =", s.count('gram'))

#ex22
name = "박보검"
if name.startswith("박"):
  print("박씨입니다.")
elif
  print("김씨입니다")

file = "HellowPython.jpg"
if
  print("그림 파일입니다")

#ex23

#ex24
s = "Python programming"
print('a' in s)
print('z' in s)
print('por' in s)
print('x' in s)

#ex25
s = input('영어 문장 입력: ')
i =0
count =0

print('모음 : ',end = '')
while i<= len(s): #len(s)-1
  if s[i] in 'aeiouAEIOU':
    count +=1
    print(s[i], end=' ')
    i+=1
print('\모음의 개수 : %d' %count)

#ex26
height = input("키를 입력하세요: ")
if 
  print("키 = "height)
else:
  print("숫자로 입력하세요")

#ex27
data = input("문자열 입력: ")
if 
  print('X', end ='')
else:
  print('O', end ='')

