# -*- coding: utf-8 -*-
"""20512심완기_수행평가 연습

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lUZzlEIICPP1dEjaJH9g2qx3m9Xge09F
"""

#1
print('I said "hellow" to you.')
print("Let'go")

wid = int(input(' 가로 : '))
hig  = int( input('세로 : '))

tot = (wid*hig)/2
print("삼각형의 면적은%d입니다."%(tot))

h = int(input('현재 시 : '))
m  = int( input('현재 분 : '))

m+=20
h =(h+m//60)%24 # //몫(정수형)
m=m%60

print("20분 뒤에는%d시 %d분입니다."%(h,m))



#5
password = input("아이디 입력: ")
level = int(input("회원 레벨 입력: "))
if password == "admin" or level == 1:
    print("관리자.")
else:
  print("관리자 아님")

num1 = int(input("첫수:"))
num2 = int(input("둘수:"))
num3 = int(input("셋수:"))
if num2 <= num1 and num3<=num1 :
  print("큰수 %.0f"%(num1))
elif num1 <= num2 and num3<=num2 :
  print("큰수 %.0f"%(num2))
else:
  print("가장 큰수 %.0f"%(num3))

age = int(input("나이:"))
if 0 <= age <=7:
  print("어린")
elif 8 <= age <=13:
  print("초등")
elif 14 <= age <=16:
  print("중등")
elif 17<= age <=19:
  print("고등")
else:
  print("성인")

cal = int(input("점수:"))
if  cal <70:
  print("F등급")
elif 70 <= cal <80:
  print("C등급")
elif 80 <= cal <90:
  print("B등급")
elif 90<= cal :
  print("A등급")
else:
  print("?")

num = int(input("숫자입력:"))
if num%3 == 0 and num%5 ==0 :
  print("3,5공배수")
elif num%3 ==0 and num%5 !=0 :
  print("3배수")
else:
  print("3의 배수 x")

a = 1;

while(a < 20):
    if(a%2 != 0):
      print( a , end=" ");
    a+=1

#11
x = 1
sum = 0

while x < 11:
    sum = sum + x
    x = x+1
    print("num값 : %d 합계 %d "%(x-1,num))

#15

import random
again = 'y'
print("주사위 게임을 시작합니다")

while again=='y':
  print('주사위를 던졌습니다')
  me=random.randint(1, 6)
  you=random.randint(1, 6)

  print("나 : %d"%me)
  print("당신 : %d"%you)

  if me > you:
    print('나의승리')
  elif me < you:
    print("당신의 승리")
  else:
    print('무승부!')
  y
  again=(input("계속하려면 y입력 : "))

#17

num = int(input('숫자입력 : '))

while num !=0 :
  print(num%10, end=' ')
  num = num//10

#18
dan = int(input("원하는 단? "))

for a in range(1, 10):
 print("%d*%d=%d"%(dan,a,dan*a))
 a+=1

